#默认为开发环境
spring:
  profiles:
    active: dev
mybatis:
  mapper-locations: classpath:dao/*.xml,classpath:mapper/*.xml
swagger:
  description: "yumi-mall查询服务接口"
  scan:
    path: com.yumi.mall.search.controller
logging:
  level:
    root: info
    com.yumi.mall.search: debug
#  path: /var/logs
  file: logs/yumi-search-logs