#默认为开发环境
spring:
  profiles:
    active: dev
  application:
    name: yumi-mall-home
mybatis:
  mapper-locations: classpath:dao/*.xml,classpath:mapper/*.xml
swagger:
  description: "yumi-mall首页服务接口"
  scan:
    path: com.yumi.mall.home.controller
logging:
  level:
    root: info
    com.yumi.mall.home: debug
#  path: logs
  file: logs/yumi-home-logs