#默认为开发环境
spring:
  profiles:
    active: dev
mybatis:
  mapper-locations: classpath:dao/*.xml,classpath:mapper/*.xml
swagger:
  description: "yumi-mall购物车服务接口"
  scan:
    path: com.yumi.mall.cartItem.controller
logging:
  level:
    root: info
    com.yumi.mall.carItem: debug
#  path: /var/logs
  file: logs/yumi-cartItem-logs
