#默认为开发环境
spring:
  profiles:
    active: dev
mybatis:
  mapper-locations: classpath:dao/*.xml,classpath:mapper/*.xml
logging:
  level:
    root: info
    com.yumi.mall.member: debug
#  path: /var/logs
  file: logs/yumi-member-logs
