server:
  port: 9002
#===datasource start===
spring:
  application:
    name: yumi-mall-member
  datasource:
    url: jdbc:mysql://localhost:3306/yumi-mall?useUnicode=true&serverTimezone=GMT%2B8&characterEncoding=utf-8
    username: root
    password: yuyang
    druid:
      initial-size: 5
      min-idle: 10
      max-active: 20
      web-stat-filter:
        exclusions: "*.js,*.gif,*.jpg,*.png,*.css,*.ico,/druid/*"
      stat-view-servlet:
        login-username: druid
        login-password: druid
#===druid end===
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
  #===redis===
  redis:
    database: 0
    host: localhost
    port: 6379
    lettuce:
      pool:
        max-active: 100 # 连接池最大连接数（使用负值表示没有限制）
        max-idle: 100 # 连接池中的最大空闲连接
        max-wait: 6000 # 连接池最大阻塞等待时间（使用负值表示没有限制）
        min-idle: 50 # 连接池中的最小空闲连接
    timeout: 1000
redis:
  key:
    prefix:
      authCode: "portal:authCode:"
authCode:
  expire:
    seconds: 90
#===redis end===
management:
  endpoints:
    web:
      exposure:
        include: "*"