#默认为开发环境
spring:
  profiles:
    active: dev
mybatis:
  mapper-locations: classpath:dao/*.xml,classpath:mapper/*.xml
swagger:
  description: "yumi-mall会员服务接口"
  scan:
    path: com.yumi.mall.member.controller
logging:
  level:
    root: info
    com.yumi.mall.member: debug
#  path: /var/logs
  file: logs/yumi-member-logs
